default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rpg-editor_development

test:
  <<: *default
  database: rpg-editor_test

production:
  <<: *default
  database: rpg-editor_production
  username: djuks
  password: djuks
